### ISSUE TITLE
ipv6 egress traffic not working

### ISSUE THREAD

**Issue by ragunathan23** [kubernetes-sigs/ip-masq-agent#58]
Hi,
Running k8s cluster with calico as CNI. We have a usecase to connect to ipv6 device from the pod which is configured with ipv4. 

- Added ip-masq-agent to masquerade daemonset 

- It created the iptables for masquerading in the host machine

- Able to ping the ipv6 device from the container of the ip-masq-agent

- Unable to reach the ipv6 device from the container of other workloads in the same cluster. Getting **connect: Network is unreachable** when running ping6 <IPV6>

**Comment by ganeshr2** [comment]
the configuration provided in the master repo is obsolete and does not work for ipv6 usecase - pls use the latest container from gcr and try and let me know below example - 

        image: gcr.io/google-containers/ip-masq-agent-amd64:v2.5.0
        args:
            - --masq-chain=IP-MASQ
            - --enable-ipv6=true

**Comment by MrHohn** [comment]
cc @anfernee @sdmodi

**Comment by anfernee** [comment]
ip-masq-agent runs on `hostNetwork: true` which means it runs in the host network namespace. That's why you can ping ipv6 device from there. 
It could be a calico issue. can you run `ip6tables-save` on your machine and share the result to see if any iptables rules are missing?
