### ISSUE TITLE
the agent masquerades IPs unexpectedly: should it masquerade incoming traffic?

### ISSUE THREAD

**Issue by kevincantu** [kubernetes-sigs/ip-masq-agent#65]
@roy-work described it here (https://github.com/Azure/AKS/issues/2076) and I've just seen the same thing.

In a private GKE cluster (1.19.10-gke.1600) we'd set up a config to aggressively masquerade everything:
```yaml
nonMasqueradeCIDRs:
masqLinkLocal: true
```

And then while digging into something I observed that traffic which should (by virtue of my internal TCP load balancer and `externalTrafficPolicy: Local` service) be logged by the NGINX ingress controller with the _actual client source IPs_ was instead being logged with IPs from the pod subnet.

Since these clients are elsewhere in private CIDR ranges, the default list of non-masquerade CIDRs wouldn't work.  Instead I modified my config like so:
```yaml
nonMasqueradeCIDRs:
  # pod CIDR
  - 172.16.0.0/12

  # our node CIDR (including the ingress controller's internal TCP load balancer IP)
  - 10..../22

# back to default
masqLinkLocal: false
```

And as @roy-work described that fixed my problem and got NGINX the right IPs.

### Expected

I thought that setting an empty `nonMasqueradeCIDRs` list would cause source IP masquerading for _outbound_ connections (from my workloads), but leave _inbound_ connections unmodified.

There's no pod-to-pod traffic in this cluster that would suffer.  And with `externalTrafficPolicy: Local`, inbound connections shouldn't be pod-to-pod...

### Actual

In fact it seems that `nonMasqueradeCIDRs` (and `masqLinkLocal`) are meant to be comprehensive to the point where _inbound_ external traffic also has its source IPs modified!

### A suggestion

Of course if this behavior is not by design this is a bug.  But if this is intentional can we clarify the docs?

For example, where the user guide (https://kubernetes.io/docs/tasks/administer-cluster/ip-masq-agent/) says 
> **nonMasqueradeCIDRs:** A list of strings in CIDR notation that specify the non-masquerade ranges.

It would be nice to explain what a "masquerade range" is.  Perhaps say this:
> > **nonMasqueradeCIDRs:** A list of strings in CIDR notation that specify the non-masquerade ranges.  _These indicate destination IPs for which the agent won't masquerade source IPs._

At the moment I don't know where the docs are defined or I'd submit a pull req. now...

**Comment by bowei** [comment]
@kevincantu https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/administer-cluster/ip-masq-agent.md if you want to send a PR, we can review it.

/remove-lifecycle stale

**Comment by kundan2707** [comment]
@bowei  if you are agree with changes suggested by @kevincantu  i can push PR with suggested change.
