### ISSUE TITLE
Broken link to add dependencies 

### ISSUE THREAD

**Issue by kundan2707** [kubernetes-sigs/ip-masq-agent#73]
Link for instructions to add a dependency. is broken in following page:
https://github.com/kubernetes-sigs/ip-masq-agent/blob/master/CONTRIBUTING.md

**Comment by bowei** [comment]
Hi -- if you send a PR, we can merge and fix.

**Comment by MrHohn** [comment]
Fixed by https://github.com/kubernetes-sigs/ip-masq-agent/pull/74.
