### ISSUE TITLE
Newer container image is missing on gcr.io

### ISSUE THREAD

**Issue by danilo404** [kubernetes-sigs/ip-masq-agent#76]
The docker image used by the Pod on the reference DaemonSet manifest is missing:
`
% docker pull gcr.io/k8s-staging-networking/ip-masq-agent:v2.7.0
Error response from daemon: manifest for gcr.io/k8s-staging-networking/ip-masq-agent:v2.7.0 not found: manifest unknown: Failed to fetch "v2.7.0" from request "/v2/k8s-staging-networking/ip-masq-agent/manifests/v2.7.0".
`

**Comment by MrHohn** [comment]
cc @jingyuanliang
