### ISSUE TITLE
updateStrategy for clusters running since pre v1.5.

### ISSUE THREAD

**Issue by tumd** [kubernetes-sigs/ip-masq-agent#89]
Hi,

I have no idea if this is the right place for this kind of issue, nor if this is the place for a fix, but here goes;

We are seeing alerts according to [this rule](https://github.com/prometheus-operator/kube-prometheus/blob/37846483d6283645a4337b0a415d729e0e0e96c9/manifests/kubernetesControlPlane-prometheusRule.yaml#L136) for ip-masq-agent on two of our (older) clusters, but not on our newer clusters.

We noticed that these two older clusters (currently running v1.22.12-gke.500) have `.spec.updateStrategy.type` set to `OnDelete` while the other clusters have `RollingUpdate`.

According to the [docs](https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/#daemonset-update-strategy), `OnDelete` was the default pre k8s 1.5. And I think our two older clusters may have been around since then, which would also explain why these clusters still has this old default setting.

The `ip-masq-agent.yaml`-manifest in this repo doesn't specify any updateStrategy
and I figured this may be the source of this issue, and that others with long-running clusters may face the same issue.

I don't want to poke in the `kube-system` namespace manually, but this perhaps would be the occasion where it would be justified.

**Comment by MrHohn** [comment]
Interesting issue - I think it doesn't harm to put the desired update strategy in the example manifest here (RollingUpdate seems to be what we want). But it will ultimately depend on the ip-masq-agent providers on updating their own deployment.
